metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 5s



metricbeat.modules:
- module: docker
  metricsets:
    - "cpu"
    - "memory"
    - "info"
  hosts: ["unix:///var/run/docker.sock"]
  period: 5s
  enabled: true

    
output.logstash:
  hosts: ["fpp-logstash:5044"]